# Generated by Django 5.2.11 on 2026-03-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("law_id", models.CharField(db_index=True, max_length=64)),
                ("law_version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=256)),
                ("status", models.CharField(choices=[("EFFECTIVE", "EFFECTIVE"), ("REPEALED", "REPEALED")], db_index=True, default="EFFECTIVE", max_length=32)),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Law",
                "verbose_name_plural": "Laws",
                "ordering": ["law_id", "law_version"],
            },
        ),
        migrations.CreateModel(
            name="Lawset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lawset_id", models.CharField(db_index=True, max_length=64)),
                ("version", models.PositiveIntegerField()),
                ("effective_at", models.DateTimeField()),
                ("digest_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lawset",
                "verbose_name_plural": "Lawsets",
                "ordering": ["lawset_id", "-version"],
            },
        ),
        migrations.CreateModel(
            name="LawsetMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("law", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lawset_memberships", to="shared_laws.law")),
                ("lawset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="shared_laws.lawset")),
            ],
            options={
                "verbose_name": "LawsetMembership",
                "verbose_name_plural": "LawsetMemberships",
                "ordering": ["lawset", "order", "law"],
            },
        ),
        migrations.AddConstraint(
            model_name="lawset",
            constraint=models.UniqueConstraint(fields=("lawset_id", "version"), name="shared_laws_lawset_unique_id_version"),
        ),
        migrations.AddConstraint(
            model_name="law",
            constraint=models.UniqueConstraint(fields=("law_id", "law_version"), name="shared_laws_law_unique_id_version"),
        ),
        migrations.AddConstraint(
            model_name="lawsetmembership",
            constraint=models.UniqueConstraint(fields=("lawset", "law"), name="shared_laws_membership_unique_lawset_law"),
        ),
    ]
