# Generated by Django 5.2.11 on 2026-03-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '監査イベント',
                'verbose_name_plural': '監査イベント',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
