# Generated by Django 5.2.11 on 2026-03-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', '待機'), ('PROCESSING', '処理中'), ('DONE', '完了'), ('FAILED', '失敗')], db_index=True, default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ExecutionQueueItem',
                'verbose_name_plural': 'ExecutionQueueItems',
                'ordering': ['-created_at'],
            },
        ),
    ]
